# Generated by Django 5.2.4 on 2025-07-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
                ("imdb_id", models.CharField(max_length=20, unique=True)),
                ("poster_url", models.URLField(blank=True, max_length=500, null=True)),
                ("plot_summary", models.TextField(blank=True, null=True)),
                ("release_date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
